package dao;
// Generated 16-may-2025 12:26:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private Integer id;
     private Tramite tramite;
     private Usuario usuario;
     private Date fecha;
     private Date hora;
     private String estado;
     private String observaciones;

    public Cita() {
    }

	
    public Cita(Tramite tramite, Usuario usuario, Date fecha, Date hora) {
        this.tramite = tramite;
        this.usuario = usuario;
        this.fecha = fecha;
        this.hora = hora;
    }
    public Cita(Tramite tramite, Usuario usuario, Date fecha, Date hora, String estado, String observaciones) {
       this.tramite = tramite;
       this.usuario = usuario;
       this.fecha = fecha;
       this.hora = hora;
       this.estado = estado;
       this.observaciones = observaciones;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tramite getTramite() {
        return this.tramite;
    }
    
    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


