package dao;
// Generated 16-may-2025 12:26:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private String telefonoContacto;
     private String emailContacto;
     private Set incidencias = new HashSet(0);
     private Set tramites = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(String nombre) {
        this.nombre = nombre;
    }
    public Departamento(String nombre, String descripcion, String telefonoContacto, String emailContacto, Set incidencias, Set tramites) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.telefonoContacto = telefonoContacto;
       this.emailContacto = emailContacto;
       this.incidencias = incidencias;
       this.tramites = tramites;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTelefonoContacto() {
        return this.telefonoContacto;
    }
    
    public void setTelefonoContacto(String telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }
    public String getEmailContacto() {
        return this.emailContacto;
    }
    
    public void setEmailContacto(String emailContacto) {
        this.emailContacto = emailContacto;
    }
    public Set getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Set incidencias) {
        this.incidencias = incidencias;
    }
    public Set getTramites() {
        return this.tramites;
    }
    
    public void setTramites(Set tramites) {
        this.tramites = tramites;
    }

    
    public String toString(){
        return nombre;
    }



}


