package dao;
// Generated 16-may-2025 12:26:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EventoMunicipal generated by hbm2java
 */
public class EventoMunicipal  implements java.io.Serializable {


     private Integer id;
     private String titulo;
     private String descripcion;
     private Date fecha;
     private String lugar;
     private Boolean visible;

    public EventoMunicipal() {
    }

	
    public EventoMunicipal(String titulo, Date fecha) {
        this.titulo = titulo;
        this.fecha = fecha;
    }
    public EventoMunicipal(String titulo, String descripcion, Date fecha, String lugar, Boolean visible) {
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.lugar = lugar;
       this.visible = visible;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }




}


