package dao;
// Generated 16-may-2025 12:26:21 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Incidencia generated by hbm2java
 */
public class Incidencia  implements java.io.Serializable {

     private Integer id;
     private Departamento departamento;
     private Usuario usuario;
     private String titulo;
     private String descripcion;
     private String estado;
     private Date fechaReporte;

    public Incidencia() {
    }

	
    public Incidencia(Departamento departamento, Usuario usuario, String titulo) {
        this.departamento = departamento;
        this.usuario = usuario;
        this.titulo = titulo;
    }
    public Incidencia(Departamento departamento, Usuario usuario, String titulo, String descripcion, String estado, Date fechaReporte) {
       this.departamento = departamento;
       this.usuario = usuario;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaReporte = fechaReporte;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaReporte() {
        return this.fechaReporte;
    }
    
    public void setFechaReporte(Date fechaReporte) {
        this.fechaReporte = fechaReporte;
    }
    
    public String toString(){
        return "titulo: "+titulo +"descripcion: "+descripcion + "estado: "+estado+"fechaReporte "+fechaReporte;
    }




}


