package dao;
// Generated 16-may-2025 12:26:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tramite generated by hbm2java
 */
public class Tramite  implements java.io.Serializable {


     private Integer id;
     private Departamento departamento;
     private String nombre;
     private String descripcion;
     private Boolean activo;
     private Set citas = new HashSet(0);

    public Tramite() {
    }

	
    public Tramite(String nombre) {
        this.nombre = nombre;
    }
    public Tramite(Departamento departamento, String nombre, String descripcion, Boolean activo, Set citas) {
       this.departamento = departamento;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.activo = activo;
       this.citas = citas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }

    public String toString(){
        return this.departamento + ":  " + this.nombre;
    }



}


